### ISSUE TITLE
Still problems with above 2.0

### ISSUE THREAD

**Issue by 7wonders** [Suor/django-cacheops#123]
I posted issue #100 a while back. I now got around to updating to 2.2.1 and I am still getting errors. Strangely its only in very specific circumstances (i.e. it mostly works). Some kind of clash with django-reversion?

```
Traceback (most recent call last):
  File "/app/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = middleware_method(request, response)
  File "/app/venv/local/lib/python2.7/site-packages/reversion/middleware.py", line 37, in process_response
    self._close_revision(request)
  File "/app/venv/local/lib/python2.7/site-packages/reversion/middleware.py", line 28, in _close_revision
    revision_context_manager.end()
  File "/app/venv/local/lib/python2.7/site-packages/reversion/revisions.py", line 176, in end
    in manager_context.items()
  File "/app/venv/local/lib/python2.7/site-packages/reversion/revisions.py", line 175, in <genexpr>
    for obj, data
  File "/app/venv/local/lib/python2.7/site-packages/reversion/revisions.py", line 616, in <lambda>
    version_data = lambda: adapter.get_version_data(instance, self._revision_context_manager._db)
  File "/app/venv/local/lib/python2.7/site-packages/reversion/revisions.py", line 108, in get_version_data
    "serialized_data": self.get_serialized_data(obj),
  File "/app/venv/local/lib/python2.7/site-packages/reversion/revisions.py", line 92, in get_serialized_data
    fields = list(self.get_fields_to_serialize()),
  File "/app/venv/local/lib/python2.7/site-packages/django/core/serializers/__init__.py", line 122, in serialize
    s.serialize(queryset, **options)
  File "/app/venv/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 57, in serialize
    self.handle_m2m_field(obj, field)
  File "/app/venv/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 71, in handle_m2m_field
    for related in getattr(obj, field.name).iterator()]
  File "/app/venv/local/lib/python2.7/site-packages/cacheops/query.py", line 243, in iterator
    for obj in superiter(self):
  File "/app/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/app/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/app/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/app/venv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/app/venv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/app/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/venv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by 7wonders** [comment]
Started looking into this again and there is some clash somewhere between cacheops 2.2+ and django-reversions middleware. 

I then noticed on this page:

http://django-reversion.readthedocs.org/en/latest/api.html

```
Warning: Due to changes in the Django 1.6 transaction handling, revision data will be saved in a separate database transaction to the one used to save your models, even if you set ATOMIC_REQUESTS = True. If you need to ensure that your models and revisions are saved in the save transaction, please use the reversion.create_revision() context manager or decorator in combination with transaction.atomic().
```

And so I tried the above fix on the save transactions in my view and it seems to have done the job. Strange because I have an almost identical view that also has reversion backed models being saved and it doesnt create the same problem. As before, the problem does not show itself when using cacheops 2.0.

**Comment by 7wonders** [comment]
I had to rollback to 2.0, this bug still showed up in other places such as doing a Group.objects.get_or_create during a post_save signal. I will try and knock out a mini fail project that replicates it.

**Comment by Suor** [comment]
Will probably be gone after transaction support changes. Reopen if still fails with current master.
