### ISSUE TITLE
Error when using redis url

### ISSUE THREAD

**Issue by hornedbull** [Suor/django-cacheops#194]
settings.py:
```
CACHEOPS_REDIS = os.environ['REDIS_URL']
CACHEOPS_DEFAULTS = {
    'timeout': 60*2
}
CACHEOPS = {
    '*.*': {'ops': 'all'},
}
CACHEOPS_DEGRADE_ON_FAILURE = True
```
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10589d840>
Traceback (most recent call last):
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check_migrations()
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 163, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/django/db/migrations/loader.py", line 176, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 66, in applied_migrations
    return set(tuple(x) for x in self.migration_qs.values_list("app", "name"))
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/cacheops/query.py", line 258, in iterator
    cache_data = redis_client.get(cache_key)
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/cacheops/conf.py", line 67, in __getattr__
    self._setup()
  File "/Users/vatsalshah/Developer/virtualenvs/senddNXT_python351/lib/python3.5/site-packages/cacheops/conf.py", line 61, in _setup
    client = (SafeRedis if DEGRADE_ON_FAILURE else redis.StrictRedis)(**redis_conf)
TypeError: type object argument after ** must be a mapping, not str
```

**Comment by Suor** [comment]
This is only available in master branch not in any released version.

**Comment by marco-santamaria** [comment]
Same problem here with version 2.4.3 from PyPI.
But on the master branch setup.py has version 2.4.2.
Is the master branch newer or older than the last released version?

**Comment by Suor** [comment]
Master is the newest.

**Comment by marco-santamaria** [comment]
OK, I installed that. Thanks for the cool package.
When possible, a new release could be useful.
