### ISSUE TITLE
Error with pypy-5.1.1, Django-1.9,django-cacheops==2.4.3

### ISSUE THREAD

**Issue by rahulibtspl** [Suor/django-cacheops#197]
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/code/.venv_pypy/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/var/www/code/.venv_pypy/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/code/.venv_pypy/site-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/var/www/code/.venv_pypy/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/var/www/code/pypy/lib-python/2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/code/.venv_pypy/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 3, in <module>
    from django.core.management.commands.runserver import \
  File "/var/www/code/.venv_pypy/site-packages/django/core/management/commands/runserver.py", line 16, in <module>
    from django.db.migrations.executor import MigrationExecutor
  File "/var/www/code/.venv_pypy/site-packages/django/db/migrations/executor.py", line 7, in <module>
    from .loader import MigrationLoader
  File "/var/www/code/.venv_pypy/site-packages/django/db/migrations/loader.py", line 10, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/var/www/code/.venv_pypy/site-packages/django/db/migrations/recorder.py", line 12, in <module>
    class MigrationRecorder(object):
  File "/var/www/code/.venv_pypy/site-packages/django/db/migrations/recorder.py", line 26, in MigrationRecorder
    class Migration(models.Model):
  File "/var/www/code/.venv_pypy/site-packages/django/db/models/base.py", line 283, in __new__
    new_class._prepare()
  File "/var/www/code/.venv_pypy/site-packages/django/db/models/base.py", line 332, in _prepare
    ensure_default_manager(cls)
  File "/var/www/code/.venv_pypy/site-packages/django/db/models/manager.py", line 28, in ensure_default_manager
    cls.add_to_class('objects', Manager())
  File "/var/www/code/.venv_pypy/site-packages/django/db/models/base.py", line 299, in add_to_class
    value.contribute_to_class(cls, name)
  File "/var/www/code/.venv_pypy/site-packages/cacheops/query.py", line 372, in contribute_to_class
    self._no_monkey.contribute_to_class(self, cls, name)
  File "/var/www/code/.venv_pypy/site-packages/django/db/models/manager.py", line 155, in contribute_to_class
    if not self.name:
**AttributeError: 'Manager' object has no attribute 'name'**

**Comment by Suor** [comment]
Please try lastest master version from here. It might not work anyway though, there was never any effort made to make cacheops run under pypy.

**Comment by rahulibtspl** [comment]
I tried with latest version as well. It's throwing the same error. Do you have any plans to make it work with pypy ?

**Comment by Suor** [comment]
I will take a look how hard is this to do.

**Comment by rahulibtspl** [comment]
Thanks a lot.

**Comment by Suor** [comment]
Made tests run. You can try latest master now, say if it works for you.

**Comment by rahulibtspl** [comment]
Thanks sour. We tested it at our end it's working fine.
