### ISSUE TITLE
failed to lookup table_to_model(django_migrations)

### ISSUE THREAD

**Issue by PatDuJour** [Suor/django-cacheops#256]
I've recently squashed all of my migration files and regenerate them to 0001s.
And then cacheops stopped working. Here's a full trace of the error.
I populated the django_migrations table with `./manage.py migrate --fake`, and
flushed all my cache in my redis,
and I still have the same error. 
```
Traceback (most recent call last):
  File "/{path}/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/{path}/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 128, in inner_run
    self.check_migrations()
  File "/{path}/env/lib/python2.7/site-packages/django/core/management/base.py", line 422, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/{path}/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/{path}/env/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/{path}/env/lib/python2.7/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/{path}/env/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 66, in applied_migrations
    return set(tuple(x) for x in self.migration_qs.values_list("app", "name"))
  File "/{path}/env/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/{path}/env/lib/python2.7/site-packages/cacheops/query.py", line 291, in _fetch_all
    self._cache_results(cache_key, self._result_cache)
  File "/{path}/env/lib/python2.7/site-packages/cacheops/query.py", line 180, in _cache_results
    self._cond_dnfs, self._cacheprofile['timeout'], dbs=[self.db])
  File "/{path}/env/lib/python2.7/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/{path}/env/lib/python2.7/site-packages/cacheops/query.py", line 176, in _cond_dnfs
    return dnfs(self)
  File "/{path}/env/lib/python2.7/site-packages/cacheops/tree.py", line 141, in dnfs
    return query_dnf(qs.query)
  File "/{path}/env/lib/python2.7/site-packages/cacheops/tree.py", line 132, in query_dnf
    aliases = {alias for alias, (join, cnt) in izip_dicts(query.alias_map, query.alias_refcount)
  File "/{path}/env/lib/python2.7/site-packages/cacheops/tree.py", line 133, in <setcomp>
    if cnt and family_has_profile(table_to_model(join.table_name))} \
  File "/{path}/env/lib/python2.7/site-packages/funcy/calc.py", line 90, in wrapper
    raise LookupError("Failed to look up %s(%s)" % (func.__name__, arg))
LookupError: Failed to look up table_to_model(django_migrations)
```

In further debugging, it fails to perform this function: `table_to_model(join.table_name)`, but I'm wondering if you should we looking up this table, since `django_migrations` table is created by django, not from the application.

**Comment by PatDuJour** [comment]
This issue is raised in 4.0.1, I don't have this issue after Rolling back to 3.1.3

**Comment by PatDuJour** [comment]
It works just fine in 4.0 as well. it seems this line is introduced [here](https://github.com/Suor/django-cacheops/commit/4d828c6522d425024a94bf41f863db4ce2b3d2a6)

**Comment by Suor** [comment]
Are you caching migrations? As a quick fix you might stop doing that.

This shouldn't happen though, I will look into it.

**Comment by PatDuJour** [comment]
Yes, we are caching migrations. That's a good point, for the time being, I'll remove migrations from caching.

**Comment by PatDuJour** [comment]
It works now. Thanks for fixing this! @Suor
