### ISSUE TITLE
Crashes when using RawSQL

### ISSUE THREAD

**Issue by thakryptex** [Suor/django-cacheops#275]
**This line of code works if cacheops is removed** (_I mean, really removed from INSTALLED_APPS, not just turned off using CACHEOPS_ENABLED = False_):
```
users_queryset = users_queryset.filter(
    uid__in=RawSQL('SELECT DISTINCT user_id FROM *mymodel* WHERE expires_at > %s', (timezone.now(),)))
```

But if cacheops is in INSTALLED_APPS, then this error happens:
```
Traceback (most recent call last):
  File "/Users/***/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/***/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 119, in _get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/Users/***/venv/lib/python3.6/site-packages/debug_toolbar/middleware.py", line 90, in process_view
    response = panel.process_view(request, view_func, view_args, view_kwargs)
  File "/Users/***/venv/lib/python3.6/site-packages/debug_toolbar/panels/profiling.py", line 151, in process_view
    return self.profiler.runcall(view_func, *args, **view_kwargs)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cProfile.py", line 109, in runcall
    return func(*args, **kw)
  File "/Users/***/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/***/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/***/venv/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/Users/***/venv/lib/python3.6/site-packages/rest_framework/views.py", line 451, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/***/backend/views/base.py", line 178, in api_exception_handler
    raise exc
  File "/Users/***/venv/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/***/moderator/views/base.py", line 52, in get
    return self.do_command(request, *args, **kwargs)
  File "/Users/***/moderator/views/base.py", line 40, in do_command
    result = command(request, *args, **kwargs) or {}
  File "/Users/***/moderator/decorators.py", line 40, in wrapper
    return wrapped(request, *args, **kwargs)
  File "/Users/***/moderator/views/html/user_search.py", line 89, in GET
    total_users = users_queryset.count()

  File "/Users/***/venv/lib/python3.6/site-packages/cacheops/query.py", line 301, in count
    return cached_as(self)(lambda: self._no_monkey.count(self))()
  File "/Users/***/venv/lib/python3.6/site-packages/cacheops/query.py", line 84, in cached_as
    cond_dnfs = join_with(lcat, map(dnfs, querysets))
  File "/Users/***/venv/lib/python3.6/site-packages/funcy/colls.py", line 108, in join_with
    dicts = list(dicts)

  File "/Users/***/venv/lib/python3.6/site-packages/cacheops/tree.py", line 139, in dnfs
    return query_dnf(qs.query)
  File "/Users/***/venv/lib/python3.6/site-packages/cacheops/tree.py", line 126, in query_dnf
    dnf = _dnf(query.where)
  File "/Users/***/venv/lib/python3.6/site-packages/cacheops/tree.py", line 78, in _dnf
    chilren_dnfs = lmap(_dnf, where.children)

  File "/Users/***/venv/lib/python3.6/site-packages/funcy/seqs.py", line 115, in map
    return _map(make_func(f, builtin=PY2), *seqs)
  File "/Users/***/venv/lib/python3.6/site-packages/funcy/cross.py", line 16, in map
    return list(_map(f, *seqs))

  File "/Users/***/venv/lib/python3.6/site-packages/cacheops/tree.py", line 65, in _dnf
    elif isinstance(where, In) and len(where.rhs) < LONG_DISJUNCTION:

TypeError: object of type 'RawSQL' has no len()
```

**And I get the same error when use Subquery** ([like here](https://github.com/Suor/django-cacheops/issues/29)):

```
users_queryset = users_queryset.filter(
    uid__in=Subquery(MyModel.objects.filter(expires_at__gt=timezone.now()).only('user_id')))
```

**Comment by Suor** [comment]
Is this some new thing in Django? Can you write a test?

пн, 26 мар. 2018 г., 22:27 kryptex <notifications@github.com>:

**Comment by thakryptex** [comment]
@Suor,

**pip freeze piece:**
```
Django==2.0.3
django-cacheops==4.0.6
redis==2.10.6
```

**Settings looks like:**
```
INSTALLED_APPS = [
    'cacheops',
   ...
]
CACHEOPS_ENABLED = False
CACHEOPS_DEGRADE_ON_FAILURE = True
CACHEOPS_REDIS = CACHES['default']['LOCATION']
CACHEOPS_DEFAULTS = {
    'timeout': 60 * 60 * 24,
    'db_agnostic': False
}
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        ...
     }
}
```

**Tests that shows this bug:**
```
from cacheops import invalidate_all
from cacheops.transaction import transaction_states
from django.db.models import Subquery
from django.db.models.expressions import RawSQL
from django.test import TestCase
from django.utils import timezone


class BaseTestCase(TestCase):
    def setUp(self):
        from funcy import empty
        transaction_states._states, self._states = empty(transaction_states._states), transaction_states._states

        invalidate_all()

    def tearDown(self):
        transaction_states._states = self._states


class TestCacheops(BaseTestCase):

    def test_rawsql(self):
        with self.assertRaises(TypeError):
            u = User.objects.filter(
                uid__in=Subquery(MyModel.objects.filter(expires_at__gt=timezone.now()).only('user_id'))
            )
            u.count()  # raises here

    def test_subquery(self):
        with self.assertRaises(TypeError):
            u = User.objects.filter(
                uid__in=RawSQL('SELECT DISTINCT profile_id FROM mymodel WHERE expires_at > %s',
                               (timezone.now(),)))
            u.count()  # raises here

```
