### ISSUE TITLE
Disable cacheops not working during tests

### ISSUE THREAD

**Issue by caseydm** [Suor/django-cacheops#276]
I tried to use @override_settings(CACHEOPS_ENABLED=False) but it appears cacheops is still trying to hit the cache. Am I doing something wrong? My Django version is 1.8.

```
from django.test import TestCase, override_settings
@override_settings(CACHEOPS_ENABLED=False)
class TestViews(TestCase):
    def test_record_list(self):
        # test stuff
```

Result:

```
RuntimeWarning: The cacheops cache is unreachable! Error: Error 61 connecting to localhost:6379. Connection refused.
  warnings.warn("The cacheops cache is unreachable! Error: %s" % e, RuntimeWarning)
```
When I put CACHEOPS_ENABLED = False in my main settings file and run the tests, the RuntimeWarning goes away.

**Comment by Suor** [comment]
Please remove CACHEOPS_DEGRADE_ON_FAILURE and paste here a stacktrace.

**Comment by caseydm** [comment]
Ok just did that. The stacktrace was:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/test/runner.py", line 210, in run_tests
    old_config = self.setup_databases()
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/test/runner.py", line 166, in setup_databases
    **kwargs
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/test/runner.py", line 370, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 368, in create_test_db
    test_flush=not keepdb,
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/db/migrations/executor.py", line 154, in apply_migration
    self.recorder.record_applied(migration.app_label, migration.name)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 67, in record_applied
    self.migration_qs.create(app=app, name=name)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/cacheops/query.py", line 440, in _post_save
    invalidate_obj(instance)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/cacheops/invalidation.py", line 38, in invalidate_obj
    invalidate_dict(model, get_obj_dict(model, obj), using=using)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/funcy/decorators.py", line 38, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/cacheops/transaction.py", line 69, in queue_when_in_transaction
    return call()
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/funcy/decorators.py", line 55, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/cacheops/invalidation.py", line 28, in invalidate_dict
    json.dumps(obj_dict, default=str)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/redis/client.py", line 2646, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/redis/client.py", line 1911, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection.send_command(*args)
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/redis/connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/redis/connection.py", line 532, in send_packed_command
    self.connect()
  File "/Users/casey/.virtualenvs/trans/lib/python2.7/site-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.

```

**Comment by Suor** [comment]
You can try printing `settings.CACHEOPS_ENABLED` and `cacheops.conf.settings.CACHEOPS_ENABLED` to check if this is `@override_settings` or cacheops settings fault. `invalidate_dict()` should be noop but it isn't for you.

**Comment by Suor** [comment]
Oh I see, the error happens in db migration not in test, so cacheops is enabled there. If you don't want cacheops to be enabled set `CACHEOPS_ENABLED=False` before starting tests, probably use separate settings file for testing.
