### ISSUE TITLE
Using get_or_create inside transaction fails on concurent threads

### ISSUE THREAD

**Issue by M1hacka** [Suor/django-cacheops#300]
Hi.
Django 2.1, cacheops 4.0.7
The problem is generated with 2 or more concurrent threads, using get_or_create inside transaction. One thread raises `django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.`

[Trace](http://prntscr.com/kqcjck)

The bug doesn't occure if:
1. I remove transaction in which get_or_create works
2. Add nocache() before get_or_create
3. Reduce number of concurrent threads to 1

Example test (fails not always but often)
```python
class UserAppMergeTest(TestCase):
    fixtures = ['apps_app']

    def test_parallel(self):
        app = App.from_parameter(100500)

        def _test_func():
            from django.db import transaction
            with transaction.atomic(using=app.shard):
                UserAppMerge.objects.get_or_create(app=app, key='test@example.com', type='email')

        from utils.utils import exec_in_parallel
        from queue import Queue
        q = Queue()
        q.put(((), {}))
        q.put(((), {}))
        exec_in_parallel(_test_func, q, threads_count=2)
```

**Comment by Suor** [comment]
Can you please post full stack trace?

**Comment by Suor** [comment]
BTW, cacheops doesn't cache gets within `.get_or_create()`, there were some missing details in this mechanism, which were fixed in master, you can try that. However, even with no logical difference cacheops may add certain delays making existing race show itself.

**Comment by Suor** [comment]
You can also use `before_after` to make test reliable, see [this code](https://github.com/Suor/django-cacheops/blob/8ad970d55a3782fbaa027332dcc4ae1ee8c41437/tests/test_extras.py#L90-L123) for usage example.

**Comment by M1hacka** [comment]
Hi, sorry for long answer. I've installed 4.1.0, nothing has changed, I still get the bug:
```python
Error
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/query.py", line 486, in get_or_create
    return self.get(**lookup), False
  File "/home/vagrant/venv/lib/python3.6/site-packages/cacheops/query.py", line 356, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
users.models.UserAppMerge.DoesNotExist: UserAppMerge matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "users_userappmerge_app_id_type_key_e0399428_uniq"
DETAIL:  Key (app_id, type, key)=(100500, email, test@example.com) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/query.py", line 520, in _create_object_from_params
    obj = self.create(**params)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django_sharding_library/manager.py", line 47, in create
    return super(ShardQuerySet, self).create(**kwargs)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/base.py", line 717, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/base.py", line 747, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/base.py", line 830, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/base.py", line 868, in _do_insert
    using=using, raw=raw)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1133, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/venv/lib/python3.6/site-packages/cacheops/transaction.py", line 99, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "users_userappmerge_app_id_type_key_e0399428_uniq"
DETAIL:  Key (app_id, type, key)=(100500, email, test@example.com) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/cqapi/users/tests/test_models.py", line 663, in test_parallel
    exec_in_parallel(_test_func, q, threads_count=5)
  File "/vagrant/cqapi/utils/utils.py", line 913, in exec_in_parallel
    t.join()
  File "/vagrant/cqapi/utils/utils.py", line 860, in join
    raise self.exc
  File "/vagrant/cqapi/utils/utils.py", line 853, in run
    return super(ExceptionThread, self).run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/vagrant/cqapi/utils/utils.py", line 892, in _worker
    local_res = func(*args, **kwargs)
  File "/vagrant/cqapi/users/tests/test_models.py", line 653, in _test_func
    UserAppMerge.objects.get_or_create(app=app, key='test@example.com', type='email')
  File "/home/vagrant/venv/lib/python3.6/site-packages/django_sharding_library/manager.py", line 82, in wrapped
    return getattr(self.get_queryset(), func_name)(*args, **kwargs)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django_sharding_library/manager.py", line 56, in get_or_create
    return super(ShardQuerySet, self).get_or_create(defaults=defaults, **kwargs)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/query.py", line 488, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/query.py", line 524, in _create_object_from_params
    return self.get(**lookup), False
  File "/home/vagrant/venv/lib/python3.6/site-packages/cacheops/query.py", line 356, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/home/vagrant/venv/lib/python3.6/site-packages/cacheops/query.py", line 277, in _fetch_all
    return self._no_monkey._fetch_all(self)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1183, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1061, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/venv/lib/python3.6/site-packages/cacheops/transaction.py", line 99, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 437, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by Suor** [comment]
This happens then transaction is not properly rolled back. From `django.db.models.query`:
```python
    def _create_object_from_params(self, lookup, params):
        # ...
        try:
            with transaction.atomic(using=self.db):
                # ...
                # If this one is routed to other db than transaction above
                # then subsequent .get() will fail 
                obj = self.create(**params)
            return obj, True
        except IntegrityError as e:
            # This one fails
            return self.get(**lookup), False
```

So check your routing at each step. Reopen this if cacheops interferes with it.
