### ISSUE TITLE
Error with pypy-6.0.0, Django-1.8, django-cacheops-4.1

### ISSUE THREAD

**Issue by salyarka** [Suor/django-cacheops#309]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/django/core/management/base.py", line 382, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/django/core/management/base.py", line 355, in create_parser
    self.add_arguments(parser)
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/django/core/management/commands/test.py", line 52, in add_arguments
    test_runner_class = get_runner(settings, self.test_runner)
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/django/test/utils.py", line 152, in get_runner
    test_module = __import__(test_module_name, {}, {}, force_str(test_path[-1]))
  File "/home/salyarka/project/app/tests.py", line 12, in <module>
    mod = m.load_module(name)
  File "/opt/pypy2-v6.0.0-linux64/lib-python/2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/salyarka/project/app/tests.py", line 5, in <module>
    from .models import (
  File "/home/salyarka/project/app/models.py", line 48, in <module>
    class Order(models.Model):
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/django/db/models/base.py", line 189, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/django/db/models/base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/cacheops/query.py", line 428, in contribute_to_class
    if cls.__module__ != '__fake__' and family_has_profile(cls):
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/funcy/calc.py", line 44, in wrapper
    value = memory[key] = func(*args, **kwargs)
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/cacheops/utils.py", line 43, in family_has_profile
    return any(model_profile, model_family(cls))
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/cacheops/utils.py", line 38, in model_family
    return class_tree(model._meta.concrete_model or get_concrete_model(model))
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/cacheops/utils.py", line 25, in get_concrete_model
    return next(b for b in model.__mro__ if issubclass(b, models.Model) and not b._meta.abstract)
  File "/home/salyarka/.virtualenvs/pypy_venv/site-packages/cacheops/utils.py", line 25, in <genexpr>
    return next(b for b in model.__mro__ if issubclass(b, models.Model) and not b._meta.abstract)
AttributeError: type object 'Model' has no attribute '_meta'

**Comment by Suor** [comment]
```bash
(cacheops-pypy6)suor:~/projects/cacheops$ python --version
Python 2.7.13 (6.0.0+dfsg-1~ppa1~ubuntu16.04, Apr 28 2018, 03:15:13)
[PyPy 6.0.0 with GCC 5.4.0 20160609]
(cacheops-pypy6)suor:~/projects/cacheops$ pip freeze | grep Django
Django==1.8
(cacheops-pypy6)suor:~/projects/cacheops$ ./run_tests.py 
Creating test database for alias 'default'...
Destroying old test database 'default'...
Creating test database for alias 'slave'...
...................s.ss........s............................................xxsss....x...........................................s.s.....
----------------------------------------------------------------------
Ran 137 tests in 3.053s

OK (skipped=9, expected failures=3)
Destroying test database for alias 'default'...
Destroying test database for alias 'slave'...
```
No errors here, you need to be more specific.

**Comment by heikkimattila** [comment]
Seems like the cause for my problem is the django_otp.models.Device class, which inherits from basic Model but is abstract. With the current functionality it is failing, even with the check above. If I do not import that class into my code, then there seems to be no problem. But have to check if two-factor auth would still work.
Is there a way to exclude one class from the "instrumentation", e.g. with a configuration option? Or something else? (I do not yet know why the cacheops code handles this class.)

**Comment by Suor** [comment]
@heikkimattila for which model does `family_has_profile()` get called and errors out for you?

**Comment by heikkimattila** [comment]
It is the class django_otp.models.Device, i.e. a class imported from external package (e.g. https://bitbucket.org/psagers/django-otp/src/default/django-otp/django_otp/models.py). The class is not instantiated in our code, but only compared if some instance is of that class (I haven't studied in details that part of the code yet).

**Comment by Suor** [comment]
Try latest master

**Comment by heikkimattila** [comment]
With latest master  we got forward, i.e. the previous situation is handled.
The next issue was in cacheops/conf.py line 86 (model_profile), where 'app_label' is None (this .lower() raises exception). When e.g. the whole block was surrounded with Try: ...  except:\n return None then it seemed to work ok, at least a quick test with Django DebugToolbar indicated that the number of DB queries were slower. 👍 

So seems like we should really start using cacheops.

**Comment by Suor** [comment]
What kind of model do you have that doesn't have app_label? Are doing something hacky there?

**Comment by heikkimattila** [comment]
Thanks for the help and support. I turned out that the usage of _django_otp.models.Device_ in our code was old and dead code, therefore the "hacky usage". So the default 4.1 cacheops works right, and makes significant difference for our application.
 Thank you!

**Comment by Suor** [comment]
@salyarka does the latest master work for you?

**Comment by heikkimattila** [comment]
Yes, it works too.
