### ISSUE TITLE
Cannot compute Sum('field'): 'field' is an aggregate

### ISSUE THREAD

**Issue by emilt27** [Suor/django-cacheops#316]
The following example does not work after installing `cacheops`:

`AnimalGroup.objects.annotate(animals_num=Count('animals')).aggregate(total_animals=Sum('animals_num'))`

I got error message: `Cannot compute Sum('animals_num'): 'animals_num' is an aggregate`. 

Django docs: https://docs.djangoproject.com/en/2.1/topics/db/aggregation/#aggregating-annotations

My env:
- python 3.6.6 & pip 18.0
- django 2.1.1
- django-cacheops 4.1
- postgresql 9.6

**Comment by Suor** [comment]
Please post complete traceback.

**Comment by emilt27** [comment]
@Suor here:

> Traceback (most recent call last):
  File "<input>", line 1, in <module>
    Group.objects.annotate(animals_num=Count('animals')).aggregate(total_animals=Sum('animals_num'))
  File "/usr/local/lib/python3.6/site-packages/cacheops/query.py", line 312, in aggregate
    qs = self.clone().annotate(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1008, in annotate
    clone.query.add_annotation(annotation, alias, is_summary=False)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 988, in add_annotation
    summarize=is_summary)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/aggregates.py", line 49, in resolve_expression
    raise FieldError("Cannot compute %s('%s'): '%s' is an aggregate" % (c.name, name, name))

![image](https://user-images.githubusercontent.com/22050249/52615970-ad14a580-2e9f-11e9-9f53-e3e74544875a.png)

**Comment by Suor** [comment]
Doesn't look like it's cacheops related

**Comment by emilt27** [comment]
@Suor it seems it is, on the following line:
https://github.com/Suor/django-cacheops/blob/master/cacheops/query.py#L338

**Comment by Suor** [comment]
It might be. Can you write a test case for it? The process is described at the bottom of the README.

**Comment by vinhluan** [comment]
It's not related to django-cacheops. I'm having the same issue when trying to sum on an aggregate field.

**Comment by matteing** [comment]
I'm having this same issue.

**Comment by matteing** [comment]
```
Traceback (most recent call last):
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/sergio/Projects/makerlog-server/accounts/views.py", line 117, in activity_graph
    return Response(UserStats(user).activity_graph)
  File "/Users/sergio/Projects/makerlog-server/stats/stats.py", line 251, in activity_graph
    'avg': tasks.aggregate(Avg('count')).get('count__avg'),
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/cacheops/query.py", line 312, in aggregate
    qs = self.clone().annotate(*args, **kwargs)
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/django/db/models/query.py", line 1056, in annotate
    clone.query.add_annotation(annotation, alias, is_summary=False)
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1000, in add_annotation
    summarize=is_summary)
  File "/Users/sergio/.local/share/virtualenvs/makerlog-server-B0FiQlpH/lib/python3.7/site-packages/django/db/models/aggregates.py", line 57, in resolve_expression
    raise FieldError("Cannot compute %s('%s'): '%s' is an aggregate" % (c.name, name, name))
django.core.exceptions.FieldError: Cannot compute Avg('count'): 'count' is an aggregate
```
