### ISSUE TITLE
Django-cacheops not honouring DISABLE_SERVER_SIDE_CURSORS=True

### ISSUE THREAD

**Issue by peteyb** [Suor/django-cacheops#331]
Hi,

I am experiencing the following error when using cacheops. 

`
<class 'django.db.utils.OperationalError'> cursor "_django_curs_140208684635136_1196" does not exist
`

The database connection is behind pgBouncer and so I set DISABLE_SERVER_SIDE_CURSORS to True for the database connection.

Here is the cacheops config:

`
CACHEOPS_DEGRADE_ON_FAILURE = True
CACHEOPS = {
    'auth.*': {'ops': 'all', 'timeout': 60*15},
    '*.*': {'ops': (), 'timeout': 60*60},
}
`

To provide more context I am running LocustIO to perform load testing of the django application, which only demonstrates this issue when under concurrent load.

There no outstanding migration to make or run on the database.

**Comment by Suor** [comment]
Does this error go away if you remove/disable cacheops?

**Comment by peteyb** [comment]
Yes, setting `CACHEOPS_ENABLED = False` stops the error

**Comment by Suor** [comment]
What's your python and django versions?

**Comment by Suor** [comment]
Also, can you provide a complete stack trace?

**Comment by peteyb** [comment]
Sorry for the delay in responding; the decision was made to remove cacheops so we could deliver the update in time for our peak usage in September. I will liaise with the team to determine when they will be thinking of adding cacheops into the project.

**Comment by magnetbox** [comment]
I am getting the same error, although I'm not 100% certain it's the same scenario as @peteyb. I sometimes get something like `psycopg2.errors:InvalidCursorName -- cursor "_django_curs_139673368975104_1" does not exist` and sometimes get something like `django.db.utils:ProgrammingError -- cursor "_django_curs_139673368975104_1" already exists`

I am running Python 3.6.9 and Django 1.11.23. 
Here is my cacheops config:

`CACHEOPS = {
    'migrations.*': { 'ops': (), 'timeout': 0 },
    'items.Item': {
        'ops': 'all',
        'timeout': 60*5,
        'cache_on_save': True
    },
    'topics.Topic': {
        'ops': 'all',
        'timeout': 60*5,
        'cache_on_save': True
    },
    'sources.Source': {
        'ops': 'all',
        'timeout': 60*60,
        'cache_on_save': True
    },
    'sites.Site': {
        'ops': 'all',
        'timeout': 60*60*24,
        'cache_on_save': True
    },
    'identifiers.Identifier': {
        'ops': 'all',
        'timeout': 60*60,
        'cache_on_save': True
    }
}
`

And here is a stack trace for psycopg2.errors:InvalidCursorName:

`
Traceback (most recent call last):
File "/app/.heroku/python/bin/celery", line 11, in <module>
File "/app/.heroku/python/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/worker.py", line 223, in run_from_argv
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/worker.py", line 258, in run
File "/app/.heroku/python/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
File "/app/.heroku/python/lib/python3.6/site-packages/celery/concurrency/base.py", line 131, in start
File "/app/.heroku/python/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 112, in on_start
File "/app/.heroku/python/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 428, in __init__
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/pool.py", line 1046, in __init__
File "/app/.heroku/python/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 445, in _create_worker_process
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/pool.py", line 1158, in _create_worker_process
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/process.py", line 124, in start
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/context.py", line 333, in _Popen
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/popen_fork.py", line 24, in __init__
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/popen_fork.py", line 79, in _launch
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/process.py", line 327, in _bootstrap
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/process.py", line 114, in run
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/pool.py", line 292, in __call__
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/pool.py", line 362, in workloop
File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 556, in _fast_trace_task
File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/application_celery.py", line 85, in wrapper
File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
File "/app/factal/topics/tasks.py", line 920, in remove_bad_topics
File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 62, in __iter__
File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 844, in results_iter
File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1292, in cursor_iter
`

And here is a stack trace for django.db.utils:ProgrammingError:

`
Traceback (most recent call last):
File "/app/.heroku/python/bin/celery", line 11, in <module>
File "/app/.heroku/python/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/worker.py", line 223, in run_from_argv
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bin/worker.py", line 258, in run
File "/app/.heroku/python/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
File "/app/.heroku/python/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
File "/app/.heroku/python/lib/python3.6/site-packages/celery/concurrency/base.py", line 131, in start
File "/app/.heroku/python/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 112, in on_start
File "/app/.heroku/python/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 428, in __init__
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/pool.py", line 1046, in __init__
File "/app/.heroku/python/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 445, in _create_worker_process
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/pool.py", line 1158, in _create_worker_process
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/process.py", line 124, in start
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/context.py", line 333, in _Popen
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/popen_fork.py", line 24, in __init__
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/popen_fork.py", line 79, in _launch
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/process.py", line 327, in _bootstrap
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/process.py", line 114, in run
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/pool.py", line 292, in __call__
File "/app/.heroku/python/lib/python3.6/site-packages/billiard/pool.py", line 362, in workloop
File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 556, in _fast_trace_task
File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/application_celery.py", line 85, in wrapper
File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
File "/app/factal/topics/tasks.py", line 845, in fill_wikipedia_data_from_url
File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
File "/app/.heroku/python/lib/python3.6/site-packages/sentry_sdk/integrations/django/__init__.py", line 446, in execute
File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
File "/app/.heroku/python/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/database_psycopg2.py", line 51, in execute
File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/database_dbapi2.py", line 25, in execute
`

**Comment by Suor** [comment]
@magnetbox I can't see cacheops anywhere in your stacktraces. Does removing/disabling cacheops removes the error?

**Comment by magnetbox** [comment]
> @magnetbox I can't see cacheops anywhere in your stacktraces. Does removing/disabling cacheops removes the error?

Yes, setting `CACHEOPS_ENABLED = False` stops the error.

**Comment by peteyb** [comment]
Closing issue, unable to invest the time in applying cacheops to the project
