### ISSUE TITLE
Issue with Lua script that manages cache keys 

### ISSUE THREAD

**Issue by KessoumML** [Suor/django-cacheops#456]
Hello !
I just updated to version 7.* and I have some issues with getting cacheops running correctly.
* Using 7.0.1 I have this error stack trace
```
Traceback (most recent call last):
  File "/code/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.9/site-packages/cacheops/apps.py", line 11, in ready
    install_cacheops()
  File "/usr/local/lib/python3.9/site-packages/funcy/flow.py", line 258, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cacheops/query.py", line 562, in install_cacheops
    if family_has_profile(model):
  File "/usr/local/lib/python3.9/site-packages/funcy/calc.py", line 62, in wrapper
    value = memory[key] = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cacheops/utils.py", line 34, in family_has_profile
    return any(model_profile, model_family(cls))
  File "/usr/local/lib/python3.9/site-packages/funcy/colls.py", line 207, in any
    return _any(xmap(pred, seq))
  File "/usr/local/lib/python3.9/site-packages/cacheops/conf.py", line 99, in model_profile
    assert not model._meta.abstract, "This should be handled by caller"
AssertionError: This should be handled by caller
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/funcy/calc.py", line 59, in wrapper
    return memory[key]
KeyError: (<class 'entity.models.record.Record'>,)
```
* Using version 7.0 I got this error stack trace:

```
File "/code/entity/models/record.py", line 55, in get
    field = Field.objects.get(**params)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cacheops/query.py", line 327, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/cacheops/query.py", line 261, in _fetch_all
    self._cache_results(cache_key, self._result_cache)
  File "/usr/local/lib/python3.9/site-packages/cacheops/query.py", line 179, in _cache_results
    cache_thing(self._prefix, cache_key, results,
  File "/usr/local/lib/python3.9/site-packages/cacheops/getset.py", line 44, in cache_thing
    load_script('cache_thing')(
  File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 4440, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 3891, in evalsha
    return self.execute_command("EVALSHA", sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1176, in execute_command
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 45, in call_with_retry
    return do()
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1177, in <lambda>
    lambda: self._send_command_parse_response(
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1153, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1192, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 829, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_1880dea5c524f6a37a650f715fa630416a2fe1fd): @user_script:50: @user_script: 50: Wrong number of args calling Redis command From Lua script
```

* I tried both `CACHEOPS_INSIDEOUT` on and off
@Suor do have any idea what's the raison of this errors please?

**Comment by KessoumML** [comment]
Thanks for the quick fix @Suor, much appreciated!
