### ISSUE TITLE
Invalidating an object with PointField value set to None fails.

### ISSUE THREAD

**Issue by sheats** [Suor/django-cacheops#98]
Here's the failing test:

```
======================================================================
ERROR: test_invalidate_model_with_geometry (tests.tests.GISTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sheats/www/django-cacheops-clearcare/tests/tests.py", line 660, in test_invalidate_model_with_geometry
    geom.save()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 664, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 170, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/sheats/www/django-cacheops-clearcare/cacheops/query.py", line 468, in _post_save
    invalidate_obj(instance)
  File "/Users/sheats/www/django-cacheops-clearcare/cacheops/invalidation.py", line 25, in invalidate_obj
    invalidate_dict(model, get_obj_dict(model, obj))
  File "/Users/sheats/www/django-cacheops-clearcare/cacheops/invalidation.py", line 55, in get_obj_dict
    for field in serializable_fields(model)
  File "/Users/sheats/www/django-cacheops-clearcare/cacheops/invalidation.py", line 55, in <genexpr>
    for field in serializable_fields(model)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/db/models/fields.py", line 169, in get_prep_value
    raise ValueError('Cannot use object with type %s for a geometry lookup parameter.' % type(geom).__name__)
ValueError: Cannot use object with type NoneType for a geometry lookup parameter.

```

**Comment by abdosalah2030** [comment]
i have same porblem
how to salve this thing

**Comment by Suor** [comment]
This issue was fixed, the test is still there and it passes. So at least your stack trace should be different or field type or something else.
